import pickle
from pathlib import Path

import pandas as pd
import streamlit as st


BASE = Path(__file__).resolve().parent
DATA_FILE = BASE / "German Credit Data.csv"
MODEL_FILE = BASE / "credit_classification_model.pkl"

# These descriptions follow the UCI Statlog German Credit data dictionary.
# DM means Deutsche Mark, the currency used when the dataset was collected.
CODE_MEANINGS = {
    "checkin_acc": {
        "A11": "Checking balance below 0 DM",
        "A12": "Checking balance from 0 to below 200 DM",
        "A13": "Checking balance at least 200 DM or salary assigned for at least 1 year",
        "A14": "No checking account",
    },
    "credit_history": {
        "A30": "No previous credit, or all credits repaid properly",
        "A31": "All previous credits at this bank repaid properly",
        "A32": "Existing credits repaid properly so far",
        "A33": "Had payment delays in the past",
        "A34": "Critical account or other credits at another bank",
    },
    "savings_acc": {
        "A61": "Savings below 100 DM",
        "A62": "Savings from 100 to below 500 DM",
        "A63": "Savings from 500 to below 1,000 DM",
        "A64": "Savings of at least 1,000 DM",
        "A65": "Unknown savings or no savings account",
    },
    "present_emp_since": {
        "A71": "Unemployed",
        "A72": "Employed for less than 1 year",
        "A73": "Employed for 1 to below 4 years",
        "A74": "Employed for 4 to below 7 years",
        "A75": "Employed for at least 7 years",
    },
    "personal_status": {
        "A91": "Male, divorced or separated",
        "A92": "Female, divorced, separated or married",
        "A93": "Male, single",
        "A94": "Male, married or widowed",
        "A95": "Female, single",
    },
    "inst_plans": {
        "A141": "Other installment plan with a bank",
        "A142": "Other installment plan with a store",
        "A143": "No other installment plan",
    },
    "job": {
        "A171": "Unemployed or unskilled, non-resident",
        "A172": "Unskilled, resident",
        "A173": "Skilled employee or official",
        "A174": "Management, self-employed or highly qualified employee",
    },
}

FIELD_LABELS = {
    "checkin_acc": "Checking account",
    "duration": "Loan duration (months)",
    "credit_history": "Credit history",
    "amount": "Loan amount (DM)",
    "savings_acc": "Savings account",
    "present_emp_since": "Current employment duration",
    "inst_rate": "Installment rate (% of disposable income, coded 1–4)",
    "personal_status": "Personal status",
    "residing_since": "Years at current residence",
    "age": "Age (years)",
    "inst_plans": "Other installment plans",
    "num_credits": "Existing credits at this bank",
    "job": "Job category",
}


@st.cache_data
def read_data():
    return pd.read_csv(DATA_FILE)


@st.cache_resource
def read_model():
    with MODEL_FILE.open("rb") as model_file:
        return pickle.load(model_file)


def make_model_input(values, model):
    # get_dummies on one row creates only the selected category's indicator.
    # Reindex to the trained statsmodels columns; omitted categories are zero.
    encoded = pd.get_dummies(pd.DataFrame([values])).astype(float)
    expected = list(model.model.exog_names)
    if "const" in expected:
        encoded["const"] = 1.0
    missing = [name for name in expected if name not in encoded.columns and name != "const"]
    unknown = [name for name in missing if name not in ALL_TRAINING_COLUMNS]
    if unknown:
        raise ValueError(f"The saved model expects unknown features: {unknown}")
    return encoded.reindex(columns=expected, fill_value=0.0)


st.set_page_config(page_title="Credit classification demo", page_icon="🏦", layout="wide")
st.title("🏦 Credit classification dashboard")
st.write("Choose the applicant details. Each category shows its original dataset code and meaning.")
st.caption("Educational demo using the historical German Credit dataset. DM means Deutsche Mark.")

if not DATA_FILE.exists():
    st.error("German Credit Data.csv is missing. Keep the CSV beside app.py.")
    st.stop()

data = read_data()
feature_data = data.drop(columns="status")
ALL_TRAINING_COLUMNS = pd.get_dummies(feature_data, drop_first=True).columns

if not MODEL_FILE.exists():
    st.info("Model file not found. Run `python train_model.py` in this folder first, then refresh the app. You can also copy the pickle generated by the credit classification notebook here.")
    st.stop()

try:
    model = read_model()
    if not hasattr(model, "model") or not hasattr(model.model, "exog_names"):
        raise TypeError("Expected the fitted statsmodels model from the credit classification notebook.")
except (OSError, pickle.UnpicklingError, TypeError, AttributeError) as error:
    st.error(f"Could not load the model: {error}")
    st.stop()

with st.form("credit_form"):
    left, right = st.columns(2)
    values = {}
    for index, column in enumerate(feature_data.columns):
        container = left if index % 2 == 0 else right
        with container:
            if column in CODE_MEANINGS:
                meanings = CODE_MEANINGS[column]
                options = sorted(feature_data[column].unique())
                values[column] = st.selectbox(
                    FIELD_LABELS[column], options,
                    format_func=lambda code, labels=meanings: f"{code} — {labels.get(code, 'Unknown code')}",
                )
            else:
                series = feature_data[column]
                values[column] = st.number_input(
                    FIELD_LABELS[column], min_value=int(series.min()),
                    max_value=int(series.max()), value=int(series.median()), step=1,
                )
    submitted = st.form_submit_button("Classify credit", type="primary")

if submitted:
    try:
        model_input = make_model_input(values, model)
        bad_probability = float(model.predict(model_input)[0])
        predicted_class = int(bad_probability >= 0.5)
        if predicted_class == 1:
            st.error("Prediction: Bad credit risk (class 1)")
        else:
            st.success("Prediction: Good credit risk (class 0)")
        st.metric("Estimated chance of bad credit", f"{bad_probability:.1%}")
        st.caption("A probability of 50% or higher is classified as bad credit. This is a model demonstration, not a lending decision.")
    except (ValueError, KeyError, TypeError, IndexError) as error:
        st.error(f"Prediction could not be made: {error}")
